# Generated by Django 4.1.1 on 2022-09-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('SIGA/UAB', 'Correspondência no SIGA/UAB'), ('SIGA/Flex', 'Correspondência no SIGA/Flexibilização Curricular'), ('Livre', 'Sem Correspondência no SIGA/Curso Livre')], max_length=9)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('matricula_inicio', models.DateTimeField()),
                ('matricula_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nome', models.CharField(help_text='Em caso de nome social, é necessário que o mesmo conste em documento emitido pela \n            Receita Federal ou Instituto de Identificação para emissão do certificado de conclusão/participação com nome social.\n            Em caso de dúvidas, procure os canais de atendimento da Receita Federal. \n        ', max_length=63, verbose_name='Nome/Nome Social')),
                ('sobrenome', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cidade', models.CharField(max_length=63)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=31)),
                ('uf', models.CharField(max_length=2)),
                ('siga', models.BooleanField()),
                ('siape', models.CharField(blank=True, max_length=7, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FormApp.curso')),
            ],
        ),
    ]
