# Generated by Django 4.1.1 on 2022-09-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosdoaluno',
            name='rua',
        ),
        migrations.AddField(
            model_name='dadosdoaluno',
            name='logradouro',
            field=models.CharField(default='Teste', max_length=255, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FormApp.curso', verbose_name='Curso Pretendido'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='siga',
            field=models.BooleanField(verbose_name='É aluno da UFJF?'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
