# Generated by Django 4.1.1 on 2022-10-10 16:38

import FormApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='cpf',
            field=models.CharField(max_length=14, validators=[FormApp.validators.validateCPF], verbose_name='CPF'),
        ),
    ]
