# Generated by Django 4.1.1 on 2022-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0003_alter_dadosdoaluno_cep_alter_dadosdoaluno_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_breve',
            field=models.CharField(default='1285006-2021.1-A', max_length=31),
            preserve_default=False,
        ),
    ]
