# Generated by Django 4.1.1 on 2022-09-27 12:06

import FormApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0005_curso_anexar_documentacao_dadosdoaluno_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anexar_documentacao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Anexar Documentação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_fim',
            field=models.DateField(verbose_name='Fim das Atividades'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(verbose_name='Início das Atividades'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='matricula_fim',
            field=models.DateTimeField(verbose_name='Fim das Inscrições'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='matricula_inicio',
            field=models.DateTimeField(verbose_name='Início das Inscrições'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_breve',
            field=models.CharField(max_length=31, verbose_name='Nome Breve'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='data_nascimento',
            field=models.DateField(validators=[FormApp.validators.validateBirthdate], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='documentacao',
            field=models.FileField(upload_to='uploads', validators=[FormApp.validators.validatePDF], verbose_name='Documentação'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
