# Generated by Django 4.1.1 on 2022-10-10 12:53

import FormApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0006_alter_curso_anexar_documentacao_alter_curso_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[FormApp.validators.validateCPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='dadosdoaluno',
            name='documentacao',
            field=models.FileField(blank=True, null=True, upload_to='uploads', validators=[FormApp.validators.validatePDF], verbose_name='Documentação'),
        ),
    ]
